mprpublish(1)
=============

Name
----
mprpublish - PKGBUILD management framework for the Makedeb Package Repository


Synopsis
--------
'mprpublish' [options] PACKAGE

'mprpublish' log [<options>] PACKAGE

'mprpublish' setup


Description
-----------
Mprpublish is an utility which helps maintainers of mpr packages to submit updates.


How it works
------------
Commit PKGBUILDs in named subdirectories.
Export them to the MPR with the mprpublish command, using the subtree push
stratagem. This preserves an independent history for third-party hosting,
pull requests... ;)

Commands
--------

*setup*::
        Initialize a new repository with git hooks.

*log* <PACKAGE>::
        View the git log of a package subtree.

Options
-------

*-p* <PACKAGE>::
        Instead of publishing, pull changes from the MPR.
        Can import packages into a new subtree.

*-s*, *--speedup* <PACKAGE>::
        Speedup future publishing by recording the subtree history during
        a push. This creates a merge commit and a second copy of all
        commits in the subtree. For more details, see the "--rejoin"
        option in linkman:git-subtree[1].

*-h*, *--help*::
        Prints a usage page.

Hooks
-----

*pre-commit*::
        Warn about whitespace errors, fail if checksums don't match, and
        auto-generate .SRCINFO for all changed PKGBUILDs.

*prepare-commit-msg*::
        Prefill the commit message with a list of added/updated/deleted
        packages + versions (if any).

Examples
--------

mprpublish setup::
        Initialize a new repository with git hooks. Refer to Hooks section
        for more info.

mprpublish -p ansible-core-git::
        Clone existing package from mpr and add its url as a git subtree to
        the currently existing git repository.

mprpublish ansible-core-git::
        Push an existing subtree to MPR.

mprpublish log::
        View the git log of a package subtree.

AUTHORS
-------
Eli Schwartz <eschwartz@archlinux.org>

canony <canony@protonmail.ch>
